[build]
  publish = "content"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/course/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"
